apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mirror
  namespace: common
spec:
  chart:
    spec:
      chart: hedera-mirror-common
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      version: '0.75.0'
  driftDetection:
    mode: warn
    ignore:
      - paths: [""]
        target:
          kind: (MutatingWebhookConfiguration|SGConfig|ValidatingWebhookConfiguration)
  install:
    crds: CreateReplace
  interval: 1m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 10
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    prometheus:
      prometheus:
        prometheusSpec:
          externalLabels:
            cluster: mainnet-staging-eu
          replicaExternalLabelName: __replica__
    traefik:
      service:
        annotations:
          cloud.google.com/neg: '{ "exposed_ports":{ "443":{"name": "mirrornode-mainnet-staging-eu"} } }'

